# Site settings
title: FreshWave
email: fresh.wave.2021@gmail.com
url: https://freshwave.github.io
description: "Wouldn't it be nice if you could cool down a product just has fast as you can heat it in a microwave?"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#2C3B8B'
  links: '#ffffff'

# Footer settings
footer: FreshWave

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/freshwaveofficial

# Build settings
markdown: kramdown
permalink: pretty
